name: AltTabPlus
options:
  bundleIdPrefix: com.yourdomain
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

targets:
  AltTabPlus:
    type: application
    platform: macOS
    sources: 
      - path: .
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"
          - "project.yml"
          - ".git"
          - ".gitignore"
          - "README.md"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourdomain.AltTabPlus
        PRODUCT_NAME: AltTabPlus
        MACOSX_DEPLOYMENT_TARGET: "14.0"
    info:
      path: Info.plist
      properties:
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        CFBundleName: AltTabPlus
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        LSUIElement: true
        NSHighResolutionCapable: true
    entitlements:
      path: AltTabPlus/AltTabPlus.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.automation.apple-events: true